# Introduction

  * What are your aims and objectives?
  * Can your research question be answered by your research strategy?
  * How are the ideas original - what are the gaps in current work?
  * What has your research done differently to advance our understanding?

Look at reviewer comments to see what are considered my successful contributions 

# The State of Visualisation and Psychology Research

The stuff that has been really successful isn't really new. It's established psychology effects applied to visualisation (attention for focus and declutter, curse of knowledge). What does this say about where we need to look for new knoweldge?

Look at: Position Paper: Are We Making Progress In Visualization Research?
and Kosara (2016) - Empire Built on Sand

Why do we need vis research?

Robert Kosara pie chart misconception work
Elting
Beyond memorability
Burns et al. (2021) - misconception about difficulty

# Precision

Cleveland and McGill
Heer and Bostock
Correll et al (2012) - Comparing Averages in Time Series Data
Why shouldn't everything be a scatterplot?

# Visualisation Literacy

What would a bias-sensitive measure of data visualisation literacy look like, given what now know about bias?

Look at: CALVI: Critical Thinking Assessment for Literacy in Visualizations

# Truncation

To what extent is there a difference in the definitions of 'axis truncation':
  * both ends vs. one end
  * bars vs. axes
  
