---
title: "Conclusion"
    
execute:
  echo: false
  warning: false
  message: false
  include: true
  
link_citations: true
---

```{r}
library(psych)
library(effectsize)
```

Data visualisations can facilitate comprehension of data by exploiting humans’ perceptual and cognitive capabilities. Systematically manipulating data visualisation designs in experimental studies can help reveal the cognitive mechanisms involved in interpretation. This, in turn, can inform recommendations for effective design, leading to successful communication of data.

Data visualisations can illuminate many aspects of a dataset, from the strength of correlations to the shape of distributions. Viewers may also form impressions of values’ absolute magnitudes: how large or small values are. To understand this process, it is necessary to examine how graphical cues contribute to a viewer’s mental representation of magnitude. Techniques from experimental psychology provide a means of investigating this aspect of cognitive processing. 

## Research Objectives

The aim of this thesis was to investigate interpretations of absolute magnitude in data visualisations. Specifically, this work sought to understand how *axis limits* may inform these judgements, with a focus on viewers’ *gist*-level representations of data, rather than their apprehension of precise values. The experiments were designed to provide insight into the cognitive mechanisms involved in assessing magnitude, by exploring how various aspects of presentation affect the processing of this information (e.g., axis orientation, colour encoding, accompanying information). Exploring various visualisation formats and various types of data yields generalisable findings. In addition, examining conventions and default settings contextualises this work within current design practices.

## Main Findings

The three sets of experiments in this thesis consider the same overarching topic: how magnitude is interpreted in data visualisations. **In general, this work demonstrates that subjective judgements of absolute magnitude are influenced by the relative position of data points within an axis. Data points which are closer to the higher end of an axis are associated with greater magnitudes.** However, each chapter provides a unique contribution.

The set of experiments in Chapter 4 manipulated axis limits in dot plots. This manipulation altered the position of plotted values, so that they appeared at high or low positions. The first experiment established that interpretations of values’ magnitude were affected by the manipulation of axis limits. In the two subsequent experiments, I explored whether judgements were influenced by the relative positions of data points within axis limits, or the absolute physical positions of data points. An inverted axis orientation made it possible to distinguish between these potential explanations. Overall, despite conventions in data visualisation design, participants rated magnitudes as greater when values appeared closer to the bottom of the visualisation, which was associated with higher numerical values. This illustrates that the *relative* positions of data points within axis limits inform magnitude judgements.

The experiment in Chapter 5 manipulated the limits of colour legends accompanying choropleth maps. Rather than altering the appearance of plotted values, this manipulation only modified the range of numerical values and corresponding colours in the maps’ colour legends. Participants interpreted magnitudes as greater when the corresponding colours for the plotted values were located at a colour legend’s upper limit, rather than its halfway point. This extends the finding from the previous set of experiments to a different type of visualisation, and illustrates that magnitude judgements are informed by the relationship between data points and axis values, not simply the appearance of plotted data points.

The set of experiments in Chapter 6 manipulated axis limits in bar charts. This manipulation compared upper axis limits based on *ggplot2*’s defaults to upper axis limits corresponding to denominator values in datasets. The first experiment established that participants interpreted magnitude as greater in the latter condition, where axes extended well above plotted values. In the subsequent experiment, I explored how awareness of numerical context affects the use of graphical cues to magnitude. When a dataset’s denominator value was not supplied in accompanying text, the degree to which axis limits informed magnitude judgements increased. This illustrates that knowledge about data points’ numerical context limits the influence of axis limits on interpretations.

The stimuli used in these experiments reveal different approaches to conveying magnitude using axis limits. The *relative frequencies* plotted as percentages in dot plots (Chapter 4) could not be less than 0 or more than 100, so axis limits were subject to logical constraints. *Absolute frequencies* plotted in bar charts (Chapter 6) were associated with denominators, so upper axis limits were intrinsically linked to datasets. Conversely, when plotting *measurements* in choropleth maps (Chapter 5), colour legend limits were not determined by denominator values. Therefore, designers must also consider the type of data at hand when identifying suitable axis limits for data visualisations. What constitutes *context* is not uniform.

## Relationship to Prior Work

Overall, this work contributes to a large body of cognitive biases which affect the interpretation of data visualisations [@dimara_task-based_2020]. In particular, it accords with other work which reports that axis limits inform subjective judgements of the magnitude of difference between values [@pandey_how_2015; @witt_graph_2019; @correll_truncating_2020; @stone_foregroundbackground_2003, @yang_truncating_2021]. Consistently observing that axis limits inform subjective judgements of *absolute* magnitude, accords with Sandman et al.’s [-@sandman_high_1994] findings, but not Freeman et al.’s [-@freeman_communicating_2021] findings, where prominent symbolic number annotations and broken axes may have reduced reliance on graphical cues to magnitude. Use of axis limits as a graphical cue can be considered an example of an *affordance* [@kindlmann_algebraic_2014] in the design of visualisations for conveying absolute magnitude, by encouraging inferences based on values’ relative positions. 

This work provides consistent evidence for the influence of *framing effects* on magnitude judgements in data visualisations. **In general terms, these effects occur when mental representation of information is affected by aspects of its *presentation* [see @verma_designing_2023; @hullman_visualization_2011], beyond the gain-loss framing in which they were originally described [@tversky_framing_1981; @kahneman_reference_1992].** This work provides evidence that axes influence interpretations by situating data points between reference points, thus carrying connotations about values’ magnitudes. This accords with other research demonstrating that subjective judgements of the same numerical value can be biased by its ranking within a set [@brown_does_2008]. Furthermore, according to models of graph comprehension, visual features are encoded prior to comprehension of precise numerical values [@pinker_theory_1990, @carpenter_model_1998]. The first impressions elicited by a data visualisation may prejudice overall interpretations [@pandey_how_2015; @yang_truncating_2021]. This explains how graphical cues to magnitude can inform judgements in spite of the availability of other relevant information (e.g., topic knowledge).

**@tbl-summary summarises previous research manipulating visualisation designs to examine the effect on interpretations of absolute magnitude, plus the results from this thesis. Like prior research, the present experiments are associated with a range of effect sizes, illustrating variability in the degree to which design choices influence judgements.**

| Investigation | Experimental manipulation | Effect Size |
| --- | --- | --- |
| @taylor_misleading_1986 | Upper axis limit in line chart | Data not provided |
| @sandman_high_1994 | Range of risk ladder | Study 1: Cohen's d = `r round(abs(m2d(m1 = 11.46, s1 =3.46, m2=12.95, s2=3.42)), digits = 2)` (`r interpret_cohens_d(m2d(m1 = 11.46, s1 =3.46, m2=12.95, s2=3.42))` effect) |
| | | Study 2: Cohen's d = `r round(abs(m2d(m1 = 11.58, s1 =3.71, m2=14.28, s2=3.43)), digits = 2)` (`r interpret_cohens_d(m2d(m1 = 11.58, s1 =3.71, m2=14.28, s2=3.43))` effect)[^1] |
| @stone_designing_2017 | Presence of stacked bars in bar chart (with identical axis limits) | Cohen’s d = 0.31[^2] (`r interpret_cohens_d(0.31)` effect) |
| @okan_designing_2018 | Upper axis limit in bar chart | $\eta^2$ = 0.05 (`r interpret_eta_squared(0.05)` effect)[^3] |
| @okan_probability_2020 | Presence of denominator information in icon array | $\eta^2$ = 0.10 (`r interpret_eta_squared(0.10)` effect) |
| @freeman_communicating_2021 | Linear versus logarithmic scales in risk ladder (Experiment 3.1) | Cohen's d = `r round(abs(m2d(m1 = 38.89, s1 =20.36, m2=40.45, s2=21.27)), digits = 2)` (`r interpret_cohens_d(m2d(m1 = 38.89, s1 =20.36, m2=40.45, s2=21.27))` effect)|
| Chapter 4 | Axis limits in dot plots | Experiment 1 - conventional orientation: Cohen’s d = 0.26 (`r interpret_cohens_d(0.26)` effect)
| | | Experiment 2 - interaction between axis limits and axis orientation: Cohen’s d = 0.66 (`r interpret_cohens_d(0.66)` effect);
| | | Experiment 3 - inverted orientation: Cohen’s d = 0.18 (`r interpret_cohens_d(0.18)` effect) |
| Chapter 5 | Upper colour legend limit in choropleth maps | $\eta^2$ = 0.90 (`r interpret_eta_squared(0.90)` effect) |
| Chapter 6 | Upper axis limit in bar charts | Experiment 1 - denominator information supplied: $\eta^2$ = 0.23 (`r interpret_eta_squared(0.23)` effect)
| | | Experiment 2 - interaction between axis limits and denominator information: $\eta^2$ = 0.21 (`r interpret_eta_squared(0.21)` effect) |

: **Summary of prior and present research on interpretation of absolute magnitude in data visualisations.** {#tbl-summary}

[^1]: **Estimated using reported sample means and standard deviations, under assumption of balanced samples: exact sample size per condition not specified.**
[^2]: **Effect size reported in @okan_probability_2020**
[^3]: **Composite perceived likelihood measure includes judgements of *relative* differences in addition to judgements of absolute magnitude.**

## Data Visualisation Literacy

The experiments in this thesis provide some evidence that the observed biases are greater for individuals with lower data visualisation literacy levels. Data visualisation literacy had a very small effect on the influence of the axis manipulation in dot plots (Chapter 4), but no effect on the influence of the colour legend manipulation in choropleth maps (Chapter 5). In Chapter 6, the effect of axis limits on the interpretation of bar charts decreased as data visualisation literacy increased, but data visualisation literacy had a smaller effect on the interaction between axis limits and accompanying information. In none of the experiments did accounting for data visualisation literacy change the pattern of results. This indicates that variation in responses cannot be exclusively attributed to data visualisation literacy levels, suggesting that the observed biases are present across individuals, albeit to different degrees.

Other data visualisation research contains mixed findings regarding the influence of data visualisation literacy. @yang_truncating_2021 found that data visualisation literacy did not predict the degree of bias associated with y-axis truncation, yet @driessen_misleading_2022 found that this bias disappeared when accounting for data visualisation literacy. However, a lack of diversity in the sample’s literacy levels in the latter experiment diminished confidence in the utility of this measure. The analysis presented in this thesis accords with observations that data visualisation literacy *interacts with* biases interpretation [@okan_individual_2012], but does not *fully explain* these biases [@okan_designing_2018].

The design of the data visualisation literacy measure used in this thesis may help explain its predictive ability. @yang_truncating_2021 suggests that it registers basic skills required for comprehending visualisations, thus may be best suited to capturing the ability to extract information from a visualisation, rather than susceptibility to design choices. @ge_calvi_2023 suggest that *critical thinking* skills predict the degree of bias elicited by deceptive designs, and have produced a data visualisation literacy measure specifically designed to capture this capacity. However, its considerable length makes it unsuitable for use in experimental studies. A shorter literacy measure of critical thinking in comprehension of data visualisations would be a valuable tool for future research. 

## Reproducibility

Historically, research on data visualisations has rarely been aligned with the principles of open and reproducible science [@haroz_open_2018]. However, sharing data, code, and materials provides transparency and allows for independent authentication of published findings [@klein_practical_2018]. The empirical work in this thesis was conducted with a focus on ensuring reproducibility. In addition to publicly sharing all data and code, I used containerisation software to capture the computational environment used for data processing, analysis and visualisation. This allows the manuscript for each chapter to be reproduced from the raw data, enhancing the transparency and sustainability of this work. Wider adoption of these open and reproducible working practices in future work would increase the credibility of data visualisation research.

## Contributions and Implications

This thesis addresses an important yet neglected topic in data visualisation research: interpretations of absolute magnitude. Experiments were designed to generate robust evidence, extending prior work on this topic [@sandman_high_1994] by increasing statistical power and investigating a range of visualisation formats. Furthermore, a focus on identifying the underlying cognitive mechanisms provides insight into how graphical cues to absolute magnitude are processed and how additional factors influence assessments (e.g.,  accompanying text). This thesis expands and strengthens the evidence base on the interpretation of absolute magnitude in data visualisations and presents new considerations for data visualisation design. 

This thesis challenges the notion of ‘objectively correct’ data visualisation design and presents a more nuanced perspective. Certainly, misrepresenting numerical values in data visualisations is an invalid practice. However, the axis manipulations explored in this thesis do not alter the numerical values presented, but the *subjective* judgements of these values. As @correll_truncating_2020 argue, because these judgements depend on context, there is no *inherently truthful* axis setting which avoids influencing viewers. **This thesis is relevant to data visualisation designers because it demonstrates that viewers appraising absolute magnitude are sensitive to the context provided by a particular design choice: axis limits. Data visualisation designers should therefore be aware of what their visualisation implies about the magnitudes of plotted data points, and faithfully portray the relevant characteristics of the dataset**. @sandman_high_1994 also assert that *intentional* design necessarily involves considering suitable interpretations. In response to the concern that this is a manipulative practice, they argue *“[I]t is no solution to renounce the intention and keep the bias”* [@sandman_high_1994, pg. 44].

A further contribution of this work is the argument that visualisation design conventions and default software settings can suppress graphical representations of absolute magnitude. For example, typical choropleth map design depicts spatial variability (i.e., *relative* differences) by mapping the maximum and minimum values to the colour legend’s upper and lower bounds, respectively. This may inappropriately imply that values near the extremes have particularly high or low *absolute* magnitudes. Rejecting this convention can assist in conveying that *all* values should be considered high or low, despite some variability. Similarly, default upper axis limits in bar charts can inflate absolute magnitude judgements, relative to axis limits based on denominator values, particularly in the absence of other contextual cues. Therefore, rejecting this default setting can assist in depicting the overall magnitude of values in the context of all possible values. However it is important to acknowledge that this default setting is unavoidable because axis limits cannot automatically account for denominators, which are not necessarily available within a dataset. Regarding the communication of absolute magnitude, issues may arise from unquestioning deference to conventions and defaults, not from the conventions and defaults themselves. Considering alternative approaches to visualisation design can facilitate appropriate presentations of data.

The present work discusses *bias*, but use of this term does not necessarily warrant a negative perspective. Automatically accepting any message conveyed by a visualisation is obviously detrimental. However, *failing* to account for visual cues to the magnitude of values could also be considered a limitation in cognitive processing. Sensitivity to the relative positions of values within an axis range, and the ability to weight this information in accordance with other knowledge, constitute powerful capabilities. Appropriate use of graphical cues to magnitude provides designers with an opportunity to leverage this bias for *effective* communication.

Sensitivity to norms in communication is another relevant factor for interpreting the findings of this thesis. Gricean pragmatic principles [@grice_logic_1975] suggest that contributions in conversation are expected to be truthful, relevant, clear, and sufficiently informative. Under the assumption that data visualisation design follows these principles, a chart’s implied message will guide viewers’ judgements. Values’ relative positions within axes would be considered relevant and reliable information, thus informing inferences about magnitude. 

## Limitations and Future Directions

This work does not suggest that conveying absolute magnitude will be appropriate in all scenarios. Other aspects of data may be considered more pertinent. Furthermore, conflicting graphical cues may prevent designers conveying magnitude *in addition to* other aspects. For example, a truncated axis may clearly display relative differences between data points but omit context illustrating the absolute magnitudes of values. Alternatively, an extended axis may clearly display absolute magnitudes but obscure the relative differences between values. A possible compromise may involve generating two visualisations: one to illustrate absolute magnitudes and another to promote discrimination between values. A similar approach is discussed in work on axis truncation [@correll_truncating_2020], and has been reported to benefit viewers [@ritchie_lie_2019]. Future work could investigate the utility of this approach for conveying both absolute magnitudes and relative differences. 

Eliciting judgements using rating scales is an established method for measuring interpretations of visualisations [see @correll_truncating_2020; @pandey_how_2015; @witt_graph_2019; @yang_truncating_2021; @stone_designing_2017; @stone_salience_2018; @okan_designing_2018; @okan_probability_2020; @sandman_high_1994]. The response scales used in this thesis sought to ensure that participants’ responses reflected message-level interpretations. Therefore, all response scales captured ratings pertaining to the *information* presented, not simply the graphical elements. However, future work employing decision-making measures would complement this work. First, this would provide insight into how conveying magnitude through axis limits influences *behaviour*. Second, this would more effectively illustrate the strength of effects observed. Measuring responses in terms of well-defined units (e.g., monetary value) can capture the magnitude of bias in a more concrete manner than rating scales. Other experiments in the field offer inspiration for effective and comprehensible decision-making tasks [e.g., @kale_visual_2020; @bancilhon_lets_2019]. 

Further investigation into the different cues to context in interpretations of absolute magnitude would provide a more detailed account of the cognitive mechanisms. There are two subtly different ways in which an axis could influence judgements, which have not been fully differentiated in this thesis. The first cue is the *numerical location* of a data point on an axis, meaning a data point may appear *numerically* large or small. The second cue is the *relative position* of a data point on an axis, meaning a data point may appear *comparatively* large or small. Future experiments could measure the relative contributions of these two cues by manipulating the numerical range of an axis whilst maintaining the approximate physical locations of data points. Alternatively, experiments could compare axes which contain only *plausible* values to axes which display the entire range of *possible* values. These investigations would reveal the degree to which an axis provides context by implying a relevant range of numerical values, versus providing a purely visual cue. The second experiment in this thesis investigated the role of numerical labels, and found that they were not used as a cue to magnitude. However, use of unfamiliar units prevented participants from considering numerical values in a typical manner. Future work comparing numerical and visual cues using familiar data would be a valuable contribution to this area. More generally, this thesis focuses on how *axis limits* inform magnitude judgements, but many other factors may also influence interpretations, from numerical units to prior beliefs. A comprehensive account of the cognitive processing of magnitude in data visualisations will also need to consider additional biases and cognitive mechanisms.

An algebraic approach to visualisation design suggests that material changes in data should be reflected accordingly in a visualisation [@kindlmann_algebraic_2014]. However, this capacity requires the ability to convey material changes in the *specific aspect* of a dataset of interest. For example, a design supporting comprehension of relative differences may be poorly suited to conveying other messages. This thesis demonstrates that conventional data visualisation formats present an opportunity for communicating an often-overlooked aspect of a dataset: absolute magnitude. Just as adjusting axis limits influences interpretations about absolute magnitude, other design choices may help convey other messages. Graphical cues to other under-explored features of data (e.g., noise and numerosity) would benefit from future investigation. Developing an understanding of cognitive processes involved in interpreting these features of data would inform effective design.

## Closing Remarks

Context makes numbers meaningful. In data visualisations, context can be established not only by plotted data points, but also extrinsic features. By determining the physical characteristics of a visualisation, designers may also influence the message conveyed about the data. Viewers’ sensitivity to the framing of data illustrates the power of design choices to mislead or enlighten. 
